// Generated by Sideko (sideko.dev)
package sideko_hacker_news

type GetAskstoriesJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetBeststoriesJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetItemIdJsonRequest struct {
    Id int `json:"id"`
    Print *string `json:"print,omitempty"`
}

type GetJobstoriesJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetMaxitemJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetNewstoriesJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetShowstoriesJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetTopstoriesJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetUpdatesJsonRequest struct {
    Print *string `json:"print,omitempty"`
}

type GetUserIdJsonRequest struct {
    Id string `json:"id"`
    Print *string `json:"print,omitempty"`
}
