// Generated by Sideko (sideko.dev)
package sideko_hacker_news
type BinaryResponse struct {
    Content []byte
    Header map[string][]string
}

type Item struct {
    By string `json:"by"`
    Dead *bool `json:"dead,omitempty"`
    Deleted *bool `json:"deleted,omitempty"`
    Descendants *int `json:"descendants,omitempty"`
    Id int `json:"id"`
    Kids *[]int `json:"kids,omitempty"`
    Parent *int `json:"parent,omitempty"`
    Parts *[]int `json:"parts,omitempty"`
    Poll *int `json:"poll,omitempty"`
    Score *int `json:"score,omitempty"`
    Text *string `json:"text,omitempty"`
    Time int `json:"time"`
    Title *string `json:"title,omitempty"`
    Type string `json:"type"`
    Url *string `json:"url,omitempty"`
}

type GetUpdatesJsonResponse struct {
    Items *[]int `json:"items,omitempty"`
    Profiles *[]string `json:"profiles,omitempty"`
}

type User struct {
    About *string `json:"about,omitempty"`
    Created *int `json:"created,omitempty"`
    Id *string `json:"id,omitempty"`
    Karma *int `json:"karma,omitempty"`
    Submitted *any `json:"submitted,omitempty"`
}
